### ISSUE TITLE
Add limited rotation

### ISSUE THREAD

**Issue by D3m0n92** [JScott/CardboardSDK-Unity#4]
Please add the possibility to insert a limit to the rotation of cardboard camera on the left, right, up and down! (Ex:  0 to 90° right) Thanks :D

**Comment by JScott** [comment]
Do you have similar software that does this that I could try as an example? What are you trying to accomplish by limiting the rotation? I'm not sure how it would be done without causing a jarring experience, perhaps even motion sickness, as you can't stop the rotation of the user's head. This seems more of a design challenge than a technical one but maybe you can help me think about it in a different way.

**Comment by D3m0n92** [comment]
The script mouse look of unity itself has this feature! Just do not get it
to work properly for cardboard! You are absolutely right for possible
disturbances related to the limitation, but I'll explain, to some
interactive scenes (in my case a launch by parachute) limit the lateral
rotation would allow me to see the backpack parachute without allowing a
360 rotation unrealistic. It can be a useful feature in these cases!

2015-04-11 20:15 GMT+02:00 Justin Scott <notifications@github.com>:

**Comment by JScott** [comment]
I've had and played games with similar issues. Wouldn't it make more sense to rotate the character model to match the user's movement or even fading out the view at a certain angle? Again, I'm not sure what this SDK could do while maintaining the illusion of virtual reality. I see a lot of games with similar problems but I don't think that restricting head movement is the right thing to endorse here.

Of course, I'd love to see a counterpoint to that in action but it's never gone well in my efforts.
